server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://savenow.ctsmoom0mww8.us-east-1.rds.amazonaws.com:3006/innodb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12341234
  application:
    name: backend
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    savenow.backend : INFO